// <auto-generated />
using System;
using Assignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240415235338_userRefranceInBooking")]
    partial class userRefranceInBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePic")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserNameChangeLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", "Identity");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.Booking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("bookings", "Identity");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.CarBooking", b =>
                {
                    b.Property<int>("bId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bId"));

                    b.Property<DateTime>("bookedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("bookedTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("bookingid")
                        .HasColumnType("int");

                    b.Property<int>("carId")
                        .HasColumnType("int");

                    b.HasKey("bId");

                    b.HasIndex("bookingid");

                    b.HasIndex("carId");

                    b.ToTable("cBookings", "Identity");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.FlightBooking", b =>
                {
                    b.Property<int>("bId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bId"));

                    b.Property<int>("bookingid")
                        .HasColumnType("int");

                    b.Property<int>("flightId")
                        .HasColumnType("int");

                    b.HasKey("bId");

                    b.HasIndex("bookingid");

                    b.HasIndex("flightId");

                    b.ToTable("fBookings", "Identity");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.HotelBooking", b =>
                {
                    b.Property<int>("bId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bId"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumRooms")
                        .HasColumnType("int");

                    b.Property<int>("bookingid")
                        .HasColumnType("int");

                    b.Property<int>("hotelId")
                        .HasColumnType("int");

                    b.HasKey("bId");

                    b.HasIndex("bookingid");

                    b.HasIndex("hotelId");

                    b.ToTable("hBookings", "Identity");
                });

            modelBuilder.Entity("Assignment.Areas.ServiceManagement.Models.Car", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("availableFrom")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("rentalCompanies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("cars", "Identity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            availableFrom = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Toronto",
                            model = "Kawasaki Ninja",
                            price = 150.0,
                            rentalCompanies = "BikeGo",
                            type = "Sports Bike"
                        },
                        new
                        {
                            id = 2,
                            availableFrom = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "New York",
                            model = "Toyota Camry",
                            price = 51.0,
                            rentalCompanies = "Rental2",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 3,
                            availableFrom = new DateTime(2024, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Los Angeles",
                            model = "Chevrolet Malibu",
                            price = 238.0,
                            rentalCompanies = "Rental3",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 4,
                            availableFrom = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Dallas",
                            model = "Ford Fusion",
                            price = 265.0,
                            rentalCompanies = "Rental4",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 5,
                            availableFrom = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Houston",
                            model = "Honda Accord",
                            price = 259.0,
                            rentalCompanies = "Rental5",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 6,
                            availableFrom = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "San Diego",
                            model = "Honda Accord",
                            price = 169.0,
                            rentalCompanies = "Rental6",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 7,
                            availableFrom = new DateTime(2024, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "New York",
                            model = "Ford Fusion",
                            price = 295.0,
                            rentalCompanies = "Rental7",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 8,
                            availableFrom = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Los Angeles",
                            model = "Honda Civic",
                            price = 95.0,
                            rentalCompanies = "Rental8",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 9,
                            availableFrom = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Houston",
                            model = "Chevrolet Malibu",
                            price = 160.0,
                            rentalCompanies = "Rental9",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 10,
                            availableFrom = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "New York",
                            model = "Honda Accord",
                            price = 57.0,
                            rentalCompanies = "Rental10",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 11,
                            availableFrom = new DateTime(2024, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Phoenix",
                            model = "Kia Forte",
                            price = 88.0,
                            rentalCompanies = "Rental11",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 12,
                            availableFrom = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Chicago",
                            model = "Kia Forte",
                            price = 240.0,
                            rentalCompanies = "Rental12",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 13,
                            availableFrom = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "San Antonio",
                            model = "Toyota Camry",
                            price = 128.0,
                            rentalCompanies = "Rental13",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 14,
                            availableFrom = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "San Diego",
                            model = "Honda Civic",
                            price = 291.0,
                            rentalCompanies = "Rental14",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 15,
                            availableFrom = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Dallas",
                            model = "Chevrolet Malibu",
                            price = 90.0,
                            rentalCompanies = "Rental15",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 16,
                            availableFrom = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Houston",
                            model = "Hyundai Elantra",
                            price = 77.0,
                            rentalCompanies = "Rental16",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 17,
                            availableFrom = new DateTime(2024, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Chicago",
                            model = "Toyota Corolla",
                            price = 100.0,
                            rentalCompanies = "Rental17",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 18,
                            availableFrom = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "San Diego",
                            model = "Kia Forte",
                            price = 154.0,
                            rentalCompanies = "Rental18",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 19,
                            availableFrom = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Chicago",
                            model = "Hyundai Elantra",
                            price = 210.0,
                            rentalCompanies = "Rental19",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 20,
                            availableFrom = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Los Angeles",
                            model = "Ford Fusion",
                            price = 263.0,
                            rentalCompanies = "Rental20",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 21,
                            availableFrom = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "San Jose",
                            model = "Hyundai Elantra",
                            price = 254.0,
                            rentalCompanies = "Rental21",
                            type = "Sports Car"
                        });
                });

            modelBuilder.Entity("Assignment.Areas.ServiceManagement.Models.Flight", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("airline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("arrTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("arrival")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("depTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("departure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maxPassanger")
                        .HasColumnType("int");

                    b.Property<int>("numPassanger")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("flights", "Identity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            airline = "Emirates",
                            arrTime = new DateTime(2024, 4, 25, 7, 20, 0, 0, DateTimeKind.Unspecified),
                            arrival = "DXB",
                            depTime = new DateTime(2024, 4, 24, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            departure = "YYZ",
                            maxPassanger = 276,
                            numPassanger = 30,
                            price = 700.0
                        },
                        new
                        {
                            id = 2,
                            airline = "British Airways",
                            arrTime = new DateTime(2024, 4, 17, 8, 56, 35, 939, DateTimeKind.Local).AddTicks(4376),
                            arrival = "CAN",
                            depTime = new DateTime(2024, 5, 5, 4, 3, 35, 939, DateTimeKind.Local).AddTicks(4239),
                            departure = "YYZ",
                            maxPassanger = 285,
                            numPassanger = 58,
                            price = 1396.0
                        },
                        new
                        {
                            id = 3,
                            airline = "Air Canada",
                            arrTime = new DateTime(2024, 4, 24, 3, 51, 35, 939, DateTimeKind.Local).AddTicks(4438),
                            arrival = "FRA",
                            depTime = new DateTime(2024, 5, 4, 4, 31, 35, 939, DateTimeKind.Local).AddTicks(4434),
                            departure = "ATL",
                            maxPassanger = 318,
                            numPassanger = 26,
                            price = 1246.0
                        },
                        new
                        {
                            id = 4,
                            airline = "Cathay Pacific",
                            arrTime = new DateTime(2024, 5, 4, 8, 36, 35, 939, DateTimeKind.Local).AddTicks(4485),
                            arrival = "CDG",
                            depTime = new DateTime(2024, 5, 11, 23, 33, 35, 939, DateTimeKind.Local).AddTicks(4481),
                            departure = "SFO",
                            maxPassanger = 230,
                            numPassanger = 184,
                            price = 1064.0
                        },
                        new
                        {
                            id = 5,
                            airline = "Cathay Pacific",
                            arrTime = new DateTime(2024, 5, 6, 22, 58, 35, 939, DateTimeKind.Local).AddTicks(4537),
                            arrival = "FRA",
                            depTime = new DateTime(2024, 5, 7, 17, 33, 35, 939, DateTimeKind.Local).AddTicks(4532),
                            departure = "PEK",
                            maxPassanger = 426,
                            numPassanger = 149,
                            price = 1263.0
                        },
                        new
                        {
                            id = 6,
                            airline = "Cathay Pacific",
                            arrTime = new DateTime(2024, 4, 30, 3, 47, 35, 939, DateTimeKind.Local).AddTicks(4596),
                            arrival = "SIN",
                            depTime = new DateTime(2024, 5, 6, 11, 41, 35, 939, DateTimeKind.Local).AddTicks(4591),
                            departure = "YYZ",
                            maxPassanger = 252,
                            numPassanger = 107,
                            price = 813.0
                        },
                        new
                        {
                            id = 7,
                            airline = "Cathay Pacific",
                            arrTime = new DateTime(2024, 5, 2, 1, 40, 35, 939, DateTimeKind.Local).AddTicks(4644),
                            arrival = "LHR",
                            depTime = new DateTime(2024, 4, 21, 12, 59, 35, 939, DateTimeKind.Local).AddTicks(4639),
                            departure = "DFW",
                            maxPassanger = 366,
                            numPassanger = 28,
                            price = 1241.0
                        },
                        new
                        {
                            id = 8,
                            airline = "Singapore Airlines",
                            arrTime = new DateTime(2024, 4, 17, 3, 3, 35, 939, DateTimeKind.Local).AddTicks(4694),
                            arrival = "HKG",
                            depTime = new DateTime(2024, 5, 15, 2, 11, 35, 939, DateTimeKind.Local).AddTicks(4689),
                            departure = "YYZ",
                            maxPassanger = 203,
                            numPassanger = 177,
                            price = 834.0
                        },
                        new
                        {
                            id = 9,
                            airline = "Emirates",
                            arrTime = new DateTime(2024, 5, 8, 1, 20, 35, 939, DateTimeKind.Local).AddTicks(4741),
                            arrival = "LHR",
                            depTime = new DateTime(2024, 5, 14, 6, 32, 35, 939, DateTimeKind.Local).AddTicks(4736),
                            departure = "SFO",
                            maxPassanger = 396,
                            numPassanger = 48,
                            price = 1324.0
                        },
                        new
                        {
                            id = 10,
                            airline = "American Airlines",
                            arrTime = new DateTime(2024, 5, 11, 18, 9, 35, 939, DateTimeKind.Local).AddTicks(4796),
                            arrival = "LHR",
                            depTime = new DateTime(2024, 4, 21, 5, 5, 35, 939, DateTimeKind.Local).AddTicks(4791),
                            departure = "ATL",
                            maxPassanger = 404,
                            numPassanger = 10,
                            price = 1102.0
                        },
                        new
                        {
                            id = 11,
                            airline = "American Airlines",
                            arrTime = new DateTime(2024, 5, 8, 4, 44, 35, 939, DateTimeKind.Local).AddTicks(4845),
                            arrival = "JFK",
                            depTime = new DateTime(2024, 4, 27, 9, 31, 35, 939, DateTimeKind.Local).AddTicks(4839),
                            departure = "DFW",
                            maxPassanger = 476,
                            numPassanger = 189,
                            price = 715.0
                        },
                        new
                        {
                            id = 12,
                            airline = "British Airways",
                            arrTime = new DateTime(2024, 5, 5, 22, 56, 35, 939, DateTimeKind.Local).AddTicks(5263),
                            arrival = "DXB",
                            depTime = new DateTime(2024, 5, 2, 2, 8, 35, 939, DateTimeKind.Local).AddTicks(5257),
                            departure = "SFO",
                            maxPassanger = 292,
                            numPassanger = 118,
                            price = 447.0
                        },
                        new
                        {
                            id = 13,
                            airline = "United Airlines",
                            arrTime = new DateTime(2024, 4, 24, 4, 12, 35, 939, DateTimeKind.Local).AddTicks(5325),
                            arrival = "JFK",
                            depTime = new DateTime(2024, 5, 7, 23, 25, 35, 939, DateTimeKind.Local).AddTicks(5320),
                            departure = "JFK",
                            maxPassanger = 222,
                            numPassanger = 175,
                            price = 1125.0
                        },
                        new
                        {
                            id = 14,
                            airline = "Air Canada",
                            arrTime = new DateTime(2024, 5, 3, 17, 44, 35, 939, DateTimeKind.Local).AddTicks(5376),
                            arrival = "CDG",
                            depTime = new DateTime(2024, 5, 14, 14, 2, 35, 939, DateTimeKind.Local).AddTicks(5370),
                            departure = "HND",
                            maxPassanger = 439,
                            numPassanger = 10,
                            price = 1240.0
                        },
                        new
                        {
                            id = 15,
                            airline = "British Airways",
                            arrTime = new DateTime(2024, 5, 3, 16, 30, 35, 939, DateTimeKind.Local).AddTicks(5428),
                            arrival = "CDG",
                            depTime = new DateTime(2024, 5, 7, 12, 13, 35, 939, DateTimeKind.Local).AddTicks(5423),
                            departure = "SFO",
                            maxPassanger = 280,
                            numPassanger = 106,
                            price = 633.0
                        },
                        new
                        {
                            id = 16,
                            airline = "Singapore Airlines",
                            arrTime = new DateTime(2024, 4, 22, 8, 56, 35, 939, DateTimeKind.Local).AddTicks(5479),
                            arrival = "AMS",
                            depTime = new DateTime(2024, 4, 23, 2, 37, 35, 939, DateTimeKind.Local).AddTicks(5474),
                            departure = "ATL",
                            maxPassanger = 266,
                            numPassanger = 166,
                            price = 1398.0
                        },
                        new
                        {
                            id = 17,
                            airline = "American Airlines",
                            arrTime = new DateTime(2024, 4, 30, 14, 23, 35, 939, DateTimeKind.Local).AddTicks(5529),
                            arrival = "CAN",
                            depTime = new DateTime(2024, 4, 23, 8, 25, 35, 939, DateTimeKind.Local).AddTicks(5524),
                            departure = "SFO",
                            maxPassanger = 359,
                            numPassanger = 56,
                            price = 1434.0
                        },
                        new
                        {
                            id = 18,
                            airline = "Air Canada",
                            arrTime = new DateTime(2024, 4, 28, 9, 26, 35, 939, DateTimeKind.Local).AddTicks(5584),
                            arrival = "CDG",
                            depTime = new DateTime(2024, 5, 10, 14, 7, 35, 939, DateTimeKind.Local).AddTicks(5579),
                            departure = "YYZ",
                            maxPassanger = 340,
                            numPassanger = 54,
                            price = 764.0
                        },
                        new
                        {
                            id = 19,
                            airline = "British Airways",
                            arrTime = new DateTime(2024, 4, 30, 12, 48, 35, 939, DateTimeKind.Local).AddTicks(5633),
                            arrival = "FRA",
                            depTime = new DateTime(2024, 5, 6, 5, 58, 35, 939, DateTimeKind.Local).AddTicks(5629),
                            departure = "LHR",
                            maxPassanger = 249,
                            numPassanger = 157,
                            price = 874.0
                        },
                        new
                        {
                            id = 20,
                            airline = "Cathay Pacific",
                            arrTime = new DateTime(2024, 5, 15, 11, 9, 35, 939, DateTimeKind.Local).AddTicks(5682),
                            arrival = "CDG",
                            depTime = new DateTime(2024, 4, 30, 1, 24, 35, 939, DateTimeKind.Local).AddTicks(5677),
                            departure = "LHR",
                            maxPassanger = 356,
                            numPassanger = 122,
                            price = 612.0
                        },
                        new
                        {
                            id = 21,
                            airline = "American Airlines",
                            arrTime = new DateTime(2024, 4, 29, 14, 33, 35, 939, DateTimeKind.Local).AddTicks(5731),
                            arrival = "LHR",
                            depTime = new DateTime(2024, 4, 28, 23, 26, 35, 939, DateTimeKind.Local).AddTicks(5726),
                            departure = "PEK",
                            maxPassanger = 475,
                            numPassanger = 78,
                            price = 682.0
                        });
                });

            modelBuilder.Entity("Assignment.Areas.ServiceManagement.Models.Hotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numRooms")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("hotels", "Identity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            amenities = "Heater, Balcony, TV, Free Breakfast",
                            city = "Toronto",
                            location = "219 Dundas St. East, Toronto, ON M5A 0V1",
                            name = "Rolex Hotel",
                            numRooms = 30,
                            price = 120.0
                        },
                        new
                        {
                            id = 2,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Philadelphia",
                            location = "572 Hilton St., San Diego, 99966",
                            name = "Ritz-Carlton",
                            numRooms = 38,
                            price = 213.0
                        },
                        new
                        {
                            id = 3,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "San Diego",
                            location = "37 Hyatt St., Phoenix, 51555",
                            name = "Hilton",
                            numRooms = 94,
                            price = 282.0
                        },
                        new
                        {
                            id = 4,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Chicago",
                            location = "629 Holiday Inn St., Dallas, 25832",
                            name = "Hilton",
                            numRooms = 63,
                            price = 110.0
                        },
                        new
                        {
                            id = 5,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Houston",
                            location = "367 Ritz-Carlton St., San Diego, 12517",
                            name = "Sheraton",
                            numRooms = 70,
                            price = 219.0
                        },
                        new
                        {
                            id = 6,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Philadelphia",
                            location = "632 Marriott St., Houston, 39365",
                            name = "Hilton",
                            numRooms = 20,
                            price = 294.0
                        },
                        new
                        {
                            id = 7,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "San Jose",
                            location = "307 Holiday Inn St., Los Angeles, 34235",
                            name = "Marriott",
                            numRooms = 23,
                            price = 262.0
                        },
                        new
                        {
                            id = 8,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Dallas",
                            location = "508 Marriott St., San Antonio, 87381",
                            name = "InterContinental",
                            numRooms = 90,
                            price = 93.0
                        },
                        new
                        {
                            id = 9,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Dallas",
                            location = "434 Sheraton St., San Antonio, 68563",
                            name = "Marriott",
                            numRooms = 58,
                            price = 137.0
                        },
                        new
                        {
                            id = 10,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Chicago",
                            location = "886 Sheraton St., Los Angeles, 49238",
                            name = "Holiday Inn",
                            numRooms = 52,
                            price = 225.0
                        },
                        new
                        {
                            id = 11,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Houston",
                            location = "530 Marriott St., Los Angeles, 94395",
                            name = "Hilton",
                            numRooms = 24,
                            price = 213.0
                        },
                        new
                        {
                            id = 12,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Philadelphia",
                            location = "742 Ritz-Carlton St., Chicago, 11408",
                            name = "Hyatt",
                            numRooms = 29,
                            price = 136.0
                        },
                        new
                        {
                            id = 13,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Phoenix",
                            location = "869 Four Seasons St., Philadelphia, 21556",
                            name = "Sheraton",
                            numRooms = 97,
                            price = 271.0
                        },
                        new
                        {
                            id = 14,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Philadelphia",
                            location = "186 InterContinental St., San Jose, 62516",
                            name = "InterContinental",
                            numRooms = 42,
                            price = 200.0
                        },
                        new
                        {
                            id = 15,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Dallas",
                            location = "667 InterContinental St., San Diego, 73390",
                            name = "Hilton",
                            numRooms = 49,
                            price = 244.0
                        },
                        new
                        {
                            id = 16,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Chicago",
                            location = "651 Hilton St., Los Angeles, 99881",
                            name = "Marriott",
                            numRooms = 36,
                            price = 160.0
                        },
                        new
                        {
                            id = 17,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "San Antonio",
                            location = "282 Four Seasons St., Phoenix, 40497",
                            name = "Ritz-Carlton",
                            numRooms = 53,
                            price = 183.0
                        },
                        new
                        {
                            id = 18,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Dallas",
                            location = "518 Hilton St., Philadelphia, 85133",
                            name = "Radisson",
                            numRooms = 65,
                            price = 249.0
                        },
                        new
                        {
                            id = 19,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "San Jose",
                            location = "374 Hyatt St., San Jose, 19327",
                            name = "Radisson",
                            numRooms = 86,
                            price = 153.0
                        },
                        new
                        {
                            id = 20,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Dallas",
                            location = "341 Hyatt St., San Diego, 29494",
                            name = "Radisson",
                            numRooms = 85,
                            price = 105.0
                        },
                        new
                        {
                            id = 21,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "San Antonio",
                            location = "704 Ritz-Carlton St., Los Angeles, 88717",
                            name = "Wyndham",
                            numRooms = 27,
                            price = 231.0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Identity");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.Booking", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.ApplicationUser", "user")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.CarBooking", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.Booking", "booking")
                        .WithMany()
                        .HasForeignKey("bookingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.Areas.ServiceManagement.Models.Car", "car")
                        .WithMany()
                        .HasForeignKey("carId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("booking");

                    b.Navigation("car");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.FlightBooking", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.Booking", "booking")
                        .WithMany()
                        .HasForeignKey("bookingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.Areas.ServiceManagement.Models.Flight", "flight")
                        .WithMany()
                        .HasForeignKey("flightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("booking");

                    b.Navigation("flight");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.HotelBooking", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.Booking", "booking")
                        .WithMany()
                        .HasForeignKey("bookingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.Areas.ServiceManagement.Models.Hotel", "hotel")
                        .WithMany()
                        .HasForeignKey("hotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("booking");

                    b.Navigation("hotel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.Areas.BookingManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
