// <auto-generated />
using System;
using Assignment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240415142554_moreData")]
    partial class moreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePic")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserNameChangeLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", "Identity");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.Booking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("bookings", "Identity");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.CarBooking", b =>
                {
                    b.Property<int>("bId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bId"));

                    b.Property<DateTime>("bookedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("bookedTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("bookingid")
                        .HasColumnType("int");

                    b.Property<int>("carId")
                        .HasColumnType("int");

                    b.HasKey("bId");

                    b.HasIndex("bookingid");

                    b.HasIndex("carId");

                    b.ToTable("cBookings", "Identity");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.FlightBooking", b =>
                {
                    b.Property<int>("bId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bId"));

                    b.Property<int>("bookingid")
                        .HasColumnType("int");

                    b.Property<int>("flightId")
                        .HasColumnType("int");

                    b.HasKey("bId");

                    b.HasIndex("bookingid");

                    b.HasIndex("flightId");

                    b.ToTable("fBookings", "Identity");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.HotelBooking", b =>
                {
                    b.Property<int>("bId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bId"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumRooms")
                        .HasColumnType("int");

                    b.Property<int>("bookingid")
                        .HasColumnType("int");

                    b.Property<int>("hotelId")
                        .HasColumnType("int");

                    b.HasKey("bId");

                    b.HasIndex("bookingid");

                    b.HasIndex("hotelId");

                    b.ToTable("hBookings", "Identity");
                });

            modelBuilder.Entity("Assignment.Areas.ServiceManagement.Models.Car", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("availableFrom")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("rentalCompanies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("cars", "Identity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            availableFrom = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Toronto",
                            model = "Kawasaki Ninja",
                            price = 150.0,
                            rentalCompanies = "BikeGo",
                            type = "Sports Bike"
                        },
                        new
                        {
                            id = 2,
                            availableFrom = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Dallas",
                            model = "Honda Accord",
                            price = 168.0,
                            rentalCompanies = "Rental2",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 3,
                            availableFrom = new DateTime(2024, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Chicago",
                            model = "Hyundai Elantra",
                            price = 66.0,
                            rentalCompanies = "Rental3",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 4,
                            availableFrom = new DateTime(2024, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "San Diego",
                            model = "Nissan Altima",
                            price = 270.0,
                            rentalCompanies = "Rental4",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 5,
                            availableFrom = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "San Diego",
                            model = "Hyundai Elantra",
                            price = 259.0,
                            rentalCompanies = "Rental5",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 6,
                            availableFrom = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Phoenix",
                            model = "Ford Fusion",
                            price = 150.0,
                            rentalCompanies = "Rental6",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 7,
                            availableFrom = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Chicago",
                            model = "Toyota Camry",
                            price = 90.0,
                            rentalCompanies = "Rental7",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 8,
                            availableFrom = new DateTime(2024, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Philadelphia",
                            model = "Nissan Altima",
                            price = 278.0,
                            rentalCompanies = "Rental8",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 9,
                            availableFrom = new DateTime(2024, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Dallas",
                            model = "Nissan Altima",
                            price = 266.0,
                            rentalCompanies = "Rental9",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 10,
                            availableFrom = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Houston",
                            model = "Ford Fusion",
                            price = 91.0,
                            rentalCompanies = "Rental10",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 11,
                            availableFrom = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Houston",
                            model = "Kia Forte",
                            price = 190.0,
                            rentalCompanies = "Rental11",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 12,
                            availableFrom = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Houston",
                            model = "Hyundai Elantra",
                            price = 78.0,
                            rentalCompanies = "Rental12",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 13,
                            availableFrom = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Dallas",
                            model = "Honda Accord",
                            price = 290.0,
                            rentalCompanies = "Rental13",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 14,
                            availableFrom = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "San Jose",
                            model = "Hyundai Elantra",
                            price = 214.0,
                            rentalCompanies = "Rental14",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 15,
                            availableFrom = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "San Diego",
                            model = "Nissan Altima",
                            price = 112.0,
                            rentalCompanies = "Rental15",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 16,
                            availableFrom = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "New York",
                            model = "Honda Accord",
                            price = 219.0,
                            rentalCompanies = "Rental16",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 17,
                            availableFrom = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "Los Angeles",
                            model = "Ford Fusion",
                            price = 256.0,
                            rentalCompanies = "Rental17",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 18,
                            availableFrom = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Houston",
                            model = "Volkswagen Jetta",
                            price = 211.0,
                            rentalCompanies = "Rental18",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 19,
                            availableFrom = new DateTime(2024, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Phoenix",
                            model = "Hyundai Elantra",
                            price = 189.0,
                            rentalCompanies = "Rental19",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 20,
                            availableFrom = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = true,
                            location = "Chicago",
                            model = "Ford Fusion",
                            price = 177.0,
                            rentalCompanies = "Rental20",
                            type = "Sports Car"
                        },
                        new
                        {
                            id = 21,
                            availableFrom = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isAvailable = false,
                            location = "San Diego",
                            model = "Nissan Altima",
                            price = 127.0,
                            rentalCompanies = "Rental21",
                            type = "Sports Car"
                        });
                });

            modelBuilder.Entity("Assignment.Areas.ServiceManagement.Models.Flight", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("airline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("arrTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("arrival")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("depTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("departure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maxPassanger")
                        .HasColumnType("int");

                    b.Property<int>("numPassanger")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("flights", "Identity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            airline = "Emirates",
                            arrTime = new DateTime(2024, 4, 25, 7, 20, 0, 0, DateTimeKind.Unspecified),
                            arrival = "DXB",
                            depTime = new DateTime(2024, 4, 24, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            departure = "YYZ",
                            maxPassanger = 276,
                            numPassanger = 30,
                            price = 700.0
                        },
                        new
                        {
                            id = 2,
                            airline = "Air Canada",
                            arrTime = new DateTime(2024, 4, 18, 17, 28, 52, 31, DateTimeKind.Local).AddTicks(520),
                            arrival = "SIN",
                            depTime = new DateTime(2024, 5, 3, 0, 42, 52, 31, DateTimeKind.Local).AddTicks(292),
                            departure = "LHR",
                            maxPassanger = 456,
                            numPassanger = 153,
                            price = 340.0
                        },
                        new
                        {
                            id = 3,
                            airline = "Singapore Airlines",
                            arrTime = new DateTime(2024, 4, 28, 12, 46, 52, 31, DateTimeKind.Local).AddTicks(583),
                            arrival = "LHR",
                            depTime = new DateTime(2024, 4, 27, 23, 14, 52, 31, DateTimeKind.Local).AddTicks(578),
                            departure = "ATL",
                            maxPassanger = 367,
                            numPassanger = 22,
                            price = 401.0
                        },
                        new
                        {
                            id = 4,
                            airline = "Singapore Airlines",
                            arrTime = new DateTime(2024, 5, 2, 13, 54, 52, 31, DateTimeKind.Local).AddTicks(637),
                            arrival = "CAN",
                            depTime = new DateTime(2024, 5, 7, 17, 58, 52, 31, DateTimeKind.Local).AddTicks(633),
                            departure = "SFO",
                            maxPassanger = 209,
                            numPassanger = 115,
                            price = 1240.0
                        },
                        new
                        {
                            id = 5,
                            airline = "Singapore Airlines",
                            arrTime = new DateTime(2024, 5, 10, 21, 58, 52, 31, DateTimeKind.Local).AddTicks(691),
                            arrival = "JFK",
                            depTime = new DateTime(2024, 5, 11, 9, 11, 52, 31, DateTimeKind.Local).AddTicks(685),
                            departure = "YYZ",
                            maxPassanger = 438,
                            numPassanger = 36,
                            price = 780.0
                        },
                        new
                        {
                            id = 6,
                            airline = "Lufthansa",
                            arrTime = new DateTime(2024, 5, 12, 18, 6, 52, 31, DateTimeKind.Local).AddTicks(745),
                            arrival = "SIN",
                            depTime = new DateTime(2024, 5, 13, 4, 36, 52, 31, DateTimeKind.Local).AddTicks(741),
                            departure = "DFW",
                            maxPassanger = 465,
                            numPassanger = 101,
                            price = 964.0
                        },
                        new
                        {
                            id = 7,
                            airline = "Cathay Pacific",
                            arrTime = new DateTime(2024, 4, 19, 15, 36, 52, 31, DateTimeKind.Local).AddTicks(792),
                            arrival = "HKG",
                            depTime = new DateTime(2024, 4, 21, 9, 49, 52, 31, DateTimeKind.Local).AddTicks(788),
                            departure = "PEK",
                            maxPassanger = 261,
                            numPassanger = 70,
                            price = 1213.0
                        },
                        new
                        {
                            id = 8,
                            airline = "United Airlines",
                            arrTime = new DateTime(2024, 4, 27, 12, 56, 52, 31, DateTimeKind.Local).AddTicks(842),
                            arrival = "LHR",
                            depTime = new DateTime(2024, 5, 3, 12, 34, 52, 31, DateTimeKind.Local).AddTicks(838),
                            departure = "CDG",
                            maxPassanger = 378,
                            numPassanger = 109,
                            price = 1276.0
                        },
                        new
                        {
                            id = 9,
                            airline = "British Airways",
                            arrTime = new DateTime(2024, 5, 11, 5, 49, 52, 31, DateTimeKind.Local).AddTicks(892),
                            arrival = "AMS",
                            depTime = new DateTime(2024, 5, 7, 16, 15, 52, 31, DateTimeKind.Local).AddTicks(887),
                            departure = "DFW",
                            maxPassanger = 212,
                            numPassanger = 165,
                            price = 551.0
                        },
                        new
                        {
                            id = 10,
                            airline = "Lufthansa",
                            arrTime = new DateTime(2024, 5, 1, 21, 56, 52, 31, DateTimeKind.Local).AddTicks(942),
                            arrival = "SIN",
                            depTime = new DateTime(2024, 5, 1, 19, 2, 52, 31, DateTimeKind.Local).AddTicks(938),
                            departure = "ATL",
                            maxPassanger = 342,
                            numPassanger = 68,
                            price = 315.0
                        },
                        new
                        {
                            id = 11,
                            airline = "Air Canada",
                            arrTime = new DateTime(2024, 4, 19, 8, 38, 52, 31, DateTimeKind.Local).AddTicks(989),
                            arrival = "LHR",
                            depTime = new DateTime(2024, 4, 24, 22, 39, 52, 31, DateTimeKind.Local).AddTicks(984),
                            departure = "HND",
                            maxPassanger = 315,
                            numPassanger = 48,
                            price = 884.0
                        },
                        new
                        {
                            id = 12,
                            airline = "Qantas",
                            arrTime = new DateTime(2024, 5, 2, 12, 41, 52, 31, DateTimeKind.Local).AddTicks(1036),
                            arrival = "ICN",
                            depTime = new DateTime(2024, 5, 3, 13, 16, 52, 31, DateTimeKind.Local).AddTicks(1032),
                            departure = "DFW",
                            maxPassanger = 325,
                            numPassanger = 94,
                            price = 1460.0
                        },
                        new
                        {
                            id = 13,
                            airline = "Cathay Pacific",
                            arrTime = new DateTime(2024, 5, 8, 20, 28, 52, 31, DateTimeKind.Local).AddTicks(1089),
                            arrival = "JFK",
                            depTime = new DateTime(2024, 4, 21, 15, 20, 52, 31, DateTimeKind.Local).AddTicks(1084),
                            departure = "DFW",
                            maxPassanger = 406,
                            numPassanger = 60,
                            price = 363.0
                        },
                        new
                        {
                            id = 14,
                            airline = "Qantas",
                            arrTime = new DateTime(2024, 4, 17, 9, 43, 52, 31, DateTimeKind.Local).AddTicks(1138),
                            arrival = "LHR",
                            depTime = new DateTime(2024, 5, 2, 19, 30, 52, 31, DateTimeKind.Local).AddTicks(1134),
                            departure = "LHR",
                            maxPassanger = 217,
                            numPassanger = 110,
                            price = 658.0
                        },
                        new
                        {
                            id = 15,
                            airline = "Delta Air Lines",
                            arrTime = new DateTime(2024, 5, 10, 20, 3, 52, 31, DateTimeKind.Local).AddTicks(1189),
                            arrival = "SIN",
                            depTime = new DateTime(2024, 5, 7, 18, 4, 52, 31, DateTimeKind.Local).AddTicks(1184),
                            departure = "SFO",
                            maxPassanger = 494,
                            numPassanger = 151,
                            price = 1049.0
                        },
                        new
                        {
                            id = 16,
                            airline = "Singapore Airlines",
                            arrTime = new DateTime(2024, 4, 22, 14, 24, 52, 31, DateTimeKind.Local).AddTicks(1239),
                            arrival = "SIN",
                            depTime = new DateTime(2024, 4, 18, 8, 14, 52, 31, DateTimeKind.Local).AddTicks(1234),
                            departure = "YYZ",
                            maxPassanger = 308,
                            numPassanger = 157,
                            price = 435.0
                        },
                        new
                        {
                            id = 17,
                            airline = "Cathay Pacific",
                            arrTime = new DateTime(2024, 5, 7, 3, 19, 52, 31, DateTimeKind.Local).AddTicks(1285),
                            arrival = "SIN",
                            depTime = new DateTime(2024, 4, 26, 23, 19, 52, 31, DateTimeKind.Local).AddTicks(1280),
                            departure = "JFK",
                            maxPassanger = 210,
                            numPassanger = 17,
                            price = 1201.0
                        },
                        new
                        {
                            id = 18,
                            airline = "American Airlines",
                            arrTime = new DateTime(2024, 4, 27, 6, 57, 52, 31, DateTimeKind.Local).AddTicks(1338),
                            arrival = "CAN",
                            depTime = new DateTime(2024, 4, 29, 6, 33, 52, 31, DateTimeKind.Local).AddTicks(1333),
                            departure = "CDG",
                            maxPassanger = 217,
                            numPassanger = 94,
                            price = 613.0
                        },
                        new
                        {
                            id = 19,
                            airline = "United Airlines",
                            arrTime = new DateTime(2024, 5, 12, 14, 54, 52, 31, DateTimeKind.Local).AddTicks(1387),
                            arrival = "CAN",
                            depTime = new DateTime(2024, 4, 21, 1, 6, 52, 31, DateTimeKind.Local).AddTicks(1382),
                            departure = "HND",
                            maxPassanger = 334,
                            numPassanger = 88,
                            price = 352.0
                        },
                        new
                        {
                            id = 20,
                            airline = "Singapore Airlines",
                            arrTime = new DateTime(2024, 4, 29, 10, 14, 52, 31, DateTimeKind.Local).AddTicks(1438),
                            arrival = "DXB",
                            depTime = new DateTime(2024, 5, 5, 4, 47, 52, 31, DateTimeKind.Local).AddTicks(1434),
                            departure = "DFW",
                            maxPassanger = 304,
                            numPassanger = 176,
                            price = 678.0
                        },
                        new
                        {
                            id = 21,
                            airline = "Cathay Pacific",
                            arrTime = new DateTime(2024, 4, 25, 13, 12, 52, 31, DateTimeKind.Local).AddTicks(1484),
                            arrival = "CDG",
                            depTime = new DateTime(2024, 5, 2, 14, 17, 52, 31, DateTimeKind.Local).AddTicks(1480),
                            departure = "YYZ",
                            maxPassanger = 337,
                            numPassanger = 82,
                            price = 1044.0
                        });
                });

            modelBuilder.Entity("Assignment.Areas.ServiceManagement.Models.Hotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numRooms")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("hotels", "Identity");

                    b.HasData(
                        new
                        {
                            id = 1,
                            amenities = "Heater, Balcony, TV, Free Breakfast",
                            city = "Toronto",
                            location = "219 Dundas St. East, Toronto, ON M5A 0V1",
                            name = "Rolex Hotel",
                            numRooms = 30,
                            price = 120.0
                        },
                        new
                        {
                            id = 2,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Houston",
                            location = "840 Marriott St., Philadelphia, 55338",
                            name = "Radisson",
                            numRooms = 69,
                            price = 271.0
                        },
                        new
                        {
                            id = 3,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Philadelphia",
                            location = "549 Holiday Inn St., Phoenix, 27316",
                            name = "Holiday Inn",
                            numRooms = 69,
                            price = 262.0
                        },
                        new
                        {
                            id = 4,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "San Antonio",
                            location = "302 Radisson St., San Jose, 31031",
                            name = "Marriott",
                            numRooms = 40,
                            price = 165.0
                        },
                        new
                        {
                            id = 5,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Chicago",
                            location = "695 Wyndham St., San Jose, 44572",
                            name = "Sheraton",
                            numRooms = 54,
                            price = 278.0
                        },
                        new
                        {
                            id = 6,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Los Angeles",
                            location = "927 Hyatt St., Chicago, 33964",
                            name = "Ritz-Carlton",
                            numRooms = 82,
                            price = 221.0
                        },
                        new
                        {
                            id = 7,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "San Jose",
                            location = "115 Wyndham St., Philadelphia, 87254",
                            name = "Marriott",
                            numRooms = 98,
                            price = 84.0
                        },
                        new
                        {
                            id = 8,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Houston",
                            location = "229 Holiday Inn St., San Diego, 71705",
                            name = "Holiday Inn",
                            numRooms = 66,
                            price = 289.0
                        },
                        new
                        {
                            id = 9,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "New York",
                            location = "120 Hilton St., Philadelphia, 31386",
                            name = "Hilton",
                            numRooms = 27,
                            price = 184.0
                        },
                        new
                        {
                            id = 10,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Philadelphia",
                            location = "58 Wyndham St., San Antonio, 21700",
                            name = "Marriott",
                            numRooms = 88,
                            price = 274.0
                        },
                        new
                        {
                            id = 11,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "San Diego",
                            location = "443 Hilton St., Dallas, 60229",
                            name = "Holiday Inn",
                            numRooms = 55,
                            price = 137.0
                        },
                        new
                        {
                            id = 12,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "San Diego",
                            location = "474 Wyndham St., Dallas, 86551",
                            name = "Marriott",
                            numRooms = 35,
                            price = 179.0
                        },
                        new
                        {
                            id = 13,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Philadelphia",
                            location = "787 Four Seasons St., San Antonio, 68030",
                            name = "Holiday Inn",
                            numRooms = 89,
                            price = 253.0
                        },
                        new
                        {
                            id = 14,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "San Antonio",
                            location = "376 InterContinental St., Los Angeles, 41412",
                            name = "Holiday Inn",
                            numRooms = 23,
                            price = 248.0
                        },
                        new
                        {
                            id = 15,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "New York",
                            location = "139 Ritz-Carlton St., Phoenix, 88739",
                            name = "Holiday Inn",
                            numRooms = 62,
                            price = 285.0
                        },
                        new
                        {
                            id = 16,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Chicago",
                            location = "62 Marriott St., San Diego, 83689",
                            name = "Four Seasons",
                            numRooms = 24,
                            price = 192.0
                        },
                        new
                        {
                            id = 17,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Los Angeles",
                            location = "458 Hilton St., San Diego, 96195",
                            name = "Wyndham",
                            numRooms = 89,
                            price = 154.0
                        },
                        new
                        {
                            id = 18,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Los Angeles",
                            location = "222 Radisson St., Los Angeles, 99490",
                            name = "Four Seasons",
                            numRooms = 24,
                            price = 160.0
                        },
                        new
                        {
                            id = 19,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Phoenix",
                            location = "476 Four Seasons St., Dallas, 63173",
                            name = "InterContinental",
                            numRooms = 62,
                            price = 115.0
                        },
                        new
                        {
                            id = 20,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Chicago",
                            location = "94 Marriott St., San Jose, 52970",
                            name = "Marriott",
                            numRooms = 62,
                            price = 151.0
                        },
                        new
                        {
                            id = 21,
                            amenities = "Wi-Fi, Air Conditioning, TV, Swimming Pool",
                            city = "Chicago",
                            location = "535 Radisson St., San Diego, 77147",
                            name = "Marriott",
                            numRooms = 39,
                            price = 181.0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "Identity");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.CarBooking", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.Booking", "booking")
                        .WithMany()
                        .HasForeignKey("bookingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.Areas.ServiceManagement.Models.Car", "car")
                        .WithMany()
                        .HasForeignKey("carId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("booking");

                    b.Navigation("car");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.FlightBooking", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.Booking", "booking")
                        .WithMany()
                        .HasForeignKey("bookingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.Areas.ServiceManagement.Models.Flight", "flight")
                        .WithMany()
                        .HasForeignKey("flightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("booking");

                    b.Navigation("flight");
                });

            modelBuilder.Entity("Assignment.Areas.BookingManagement.Models.HotelBooking", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.Booking", "booking")
                        .WithMany()
                        .HasForeignKey("bookingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.Areas.ServiceManagement.Models.Hotel", "hotel")
                        .WithMany()
                        .HasForeignKey("hotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("booking");

                    b.Navigation("hotel");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.Areas.BookingManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Assignment.Areas.BookingManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
